#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/alert_settings.sh"
/usr/bin/geth --light --rpc --port $GETH_NODE_PORT --rpcport $GETH_RPC_PORT --unlock $ACC --password /root/.scripts/p.txt
