#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/alert.conf"
/usr/bin/parity --light --jsonrpc-port=$PARITY_RPC_PORT --jsonrpc-cors=all --jsonrpc-hosts=all --jsonrpc-apis=all --port=$PARITY_NODE_PORT
