#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/alert_settings.sh"
/usr/bin/parity --light --jsonrpc-port=$PARITY_RPC_PORT --port=$PARITY_NODE_PORT --unlock $ACC --password /root/.scripts/p.txt
